###
POST http://localhost:8080/api/v1/bookings/booking
Content-Type: application/json

{
  "camper": {
    "email": "marcus@upgrade.com",
    "fullName": "Marcus"
  },
  "dateRange": {
    "startDate": "06/06/2023",
    "endDate": "06/07/2023"
  }
}

###
GET http://localhost:8080/api/v1/bookings

###
GET http://localhost:8080/api/v1/bookings/booking/1

###
PUT http://localhost:8080/api/v1/bookings/booking/1
Content-Type: application/json

{
    "startDate": "06/07/2023",
    "endDate": "06/08/2023"
}

###
DELETE http://localhost:8080/api/v1/bookings/booking/1

###
GET http://localhost:8080/api/v1/campers

###
GET http://localhost:8080/api/v1/campers/camper/1

###
GET http://localhost:8080/api/v1/reservations

###
GET http://localhost:8080/api/v1/reservations/reservation/1

###
POST http://localhost:8080/api/v1/reservations/available
Content-Type: application/json

{
  "startDate": "06/06/2023"
}

###
GET http://localhost:8080/api/v1/reservations/available
Content-Type: application/json

{
  "startDate": "06/07/2023",
  "endDate": "06/07/2023"
}