GET http://localhost:8080/api/v1/reservations

###
PUT http://localhost:8080/api/v1/reservations/duration
Content-Type: application/json

{
  "startDate": "06/05/2023",
  "duration": 3
}

###
GET http://localhost:8080/api/v1/reservations/1