GET http://localhost:8080/api/v1/reservations

###
PUT http://localhost:8080/api/v1/bookings/book
Content-Type: application/json

{
  "camper": {
    "email": "marcus@upgrade.com",
    "fullName": "Marcus"
  },
  "dateRange": {
    "startDate": "06/04/2023",
    "endDate": "06/06/2023"
  }
}

###
GET http://localhost:8080/api/v1/bookings/reservations/1

###
GET http://localhost:8080/api/v1/reservations/1